name: Addition Tests and Deployment

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Run additional script on successful tests
      if: ${{ success() }}
      run: |
        echo "Tests passed, running additional script."
        node additional-script.js
    
    - name: Run error handling script on failed tests
      if: ${{ failure() }}
      run: |
        echo "Tests failed, running error handling script."
        node error-handling.js